// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUX_0ynrBxotJIy91GZClCTPLWEqspsw',
    appId: '1:591836155357:web:28acc9e9b961345610fa34',
    messagingSenderId: '591836155357',
    projectId: 'j-cash-app',
    authDomain: 'j-cash-app.firebaseapp.com',
    storageBucket: 'j-cash-app.firebasestorage.app',
    measurementId: 'G-SDHCNC44JT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDtgk-hfPoi7bP6clLxsORxiakkNKy8Tc',
    appId: '1:591836155357:ios:2ec977bfa266743110fa34',
    messagingSenderId: '591836155357',
    projectId: 'j-cash-app',
    storageBucket: 'j-cash-app.firebasestorage.app',
    iosBundleId: 'com.example.jCash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDtgk-hfPoi7bP6clLxsORxiakkNKy8Tc',
    appId: '1:591836155357:ios:2ec977bfa266743110fa34',
    messagingSenderId: '591836155357',
    projectId: 'j-cash-app',
    storageBucket: 'j-cash-app.firebasestorage.app',
    iosBundleId: 'com.example.jCash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvUX_0ynrBxotJIy91GZClCTPLWEqspsw',
    appId: '1:591836155357:web:2c5db36544d0366510fa34',
    messagingSenderId: '591836155357',
    projectId: 'j-cash-app',
    authDomain: 'j-cash-app.firebaseapp.com',
    storageBucket: 'j-cash-app.firebasestorage.app',
    measurementId: 'G-EWSKM700H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbkKiojKl-zkyKNnlS47iLCY_Z8zXG9uU',
    appId: '1:591836155357:android:b1ab5a231ab6386510fa34',
    messagingSenderId: '591836155357',
    projectId: 'j-cash-app',
    storageBucket: 'j-cash-app.firebasestorage.app',
  );
}
